theme: minima
title: Learning Github Pages
author: Vidya Kadam
email: vidya-kadam@github.com
description: > # this means to ignore newlines until "baseurl:"
This site is my learning about creating, editing and applying themes on Github Pages and creating my first blog site.

# social links
twitter_username: VidyaKJ # DO NOT include the @ character, or else the build will fail!
github_username:  vidya-kadam # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
